version: '3'
services:
  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "88:80"
    environment:
      - VITE_MICROSERVICE_IP=127.0.0.1
      - VITE_MICROSERVICE_PORT=80
      - VITE_NFL_URL=https://api.sportsdata.io/
      - VITE_API_KEY=efb56e725ab0490c89730b91c0d7bb60
      - API_HOST=backend
      - PORT=8080

  microservice:
    container_name: microservice
    build: ./microservice/
    restart: always
    ports:
      - "80:80"
